jpackage --type msi ^
  --dest output ^
  --name "ExamDesk" ^
  --input dist/ ^
  --main-jar ExamDesk-1.0.jar ^
  --main-class av.entrance.client.Launcher ^
  --icon "src/main/resources/av/entrance/client/images/logos/logo.ico" ^
  --vendor "Aayush Vishwakarma" ^
  --app-version "1.0.0" ^
  --description "Exam Management and Entrance Application" ^
  --copyright "Copyright 2026 Aayush Vishwakarma" ^
  --win-dir-chooser ^
  --win-shortcut ^
  --license-file LICENSE.txt ^
  --win-menu ^
  --win-menu-group "AV Apps" ^
  --about-url "https://github.com/vAayush3301/ggps-entrance-client"